version: "2.2"

services:

  mysql:
    image: mysql:8.0.32
    volumes:
      - ./storage:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234yes
      - MYSQL_USER=yes
      - MYSQL_DATABASE=yes